<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\HybridRelations;

class Package extends Eloquent
{
    use HybridRelations;

    protected $connection = 'mongodb';
    protected $collection = 'package';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        "transaction_id",
        "customer_name",
        "customer_code",
        "transaction_amount",
        "transaction_discount",
        "transaction_additional_field",
        "transaction_payment_type",
        "transaction_state",
        "transaction_code",
        "transaction_order",
        "location_id",
        "organization_id",
        "created_at",
        "updated_at",
        "transaction_payment_type_name",
        "transaction_cash_amount",
        "transaction_cash_change",
        "customer_attribute",
        "connote",
        "connote_id",
        "origin_data",
        "destination_data",
        "koli_data",
        "custom_field",
        "currentLocation",
    ];

    public static $rules = [
        "transaction_id" => "required|string",
        "customer_name" => "required|string",
        "customer_code" => "required|string|max:7|min:7",
        "transaction_amount" => "required|integer",
        "transaction_discount" => "required|integer",
        "transaction_additional_field" => "string|nullable",
        "transaction_payment_type" => "required|numeric",
        "transaction_state" => "required|string",
        "transaction_code" => "required|string|max:16|min:16",
        "transaction_order" => "required|numeric",
        "location_id" => "required|string",
        "organization_id" => "required|numeric",
        "created_at" => "required",
        "updated_at" => "required",
        "transaction_payment_type_name" => "required|string",
        "transaction_cash_amount" => "required|integer",
        "transaction_cash_change" => "required|integer",
        "customer_attribute*.Nama_Sales" => "required|string",
        "customer_attribute*.TOP" => "required|string",
        "customer_attribute*.Jenis_Pelanggan" => "required|string",
        "connote*.connote_id" => "required|uuid",
        "connote*.connote_number" => "required|numeric",
        "connote*.connote_service" => "required|string",
        "connote*.connote_service_price" => "required|integer",
        "connote*.connote_amount" => "required|integer",
        "connote*.connote_code" => "required|string",
        "connote*.connote_booking_code" => "string|nullable",
        "connote*.connote_order" => "required|numeric",
        "connote*.connote_state" => "required|string",
        "connote*.connote_state_id" => "required|numeric",
        "connote*.zone_code_from" => "required|string",
        "connote*.zone_code_to" => "required|string",
        "connote*.surcharge_amount" => "integer|nullable",
        "connote*.transaction_id" => "required|uuid",
        "connote*.actual_weight" => "required|integer",
        "connote*.volume_weight" => "required|integer",
        "connote*.chargeable_weight" => "required|integer",
        "connote*.created_at" => "required",
        "connote*.updated_at" => "required",
        "connote*.organization_id" => "required|numeric",
        "connote*.location_id" => "required|string",
        "connote*.connote_total_package" => "required|integer",
        "connote*.connote_surcharge_amount" => "required|integer|nullable",
        "connote*.connote_sla_day" => "required|integer",
        "connote*.location_name" => "required|string",
        "connote*.location_type" => "required|string",
        "connote*.source_tariff_db" => "required|string",
        "connote*.id_source_tariff" => "required|numeric",
        "connote*.pod" => "string|nullable",
        "connote_id" => "required|uuid",
        "origin_data*.customer_name" => "required|string",
        "origin_data*.customer_address" => "required|string",
        "origin_data*.customer_email" => "email",
        "origin_data*.customer_phone" => "required|string",
        "origin_data*.customer_address_detail" => "string|nullable",
        "origin_data*.customer_zip_code" => "required|numeric",
        "origin_data*.zone_code" => "required|string",
        "origin_data*.organization_id" => "required|numeric",
        "origin_data*.location_id" => "required|string",
        "destination_data*.customer_name" => "required|string",
        "destination_data*.customer_address" => "required|string",
        "destination_data*.customer_email" => "email|nullable",
        "destination_data*.customer_phone" => "required|string",
        "destination_data*.customer_address_detail" => "string|nullable",
        "destination_data*.customer_zip_code" => "required|numeric",
        "destination_data*.zone_code" => "required|string",
        "destination_data*.organization_id" => "required|numeric",
        "destination_data*.location_id" => "required|string",
        "koli_data*.koli_length" => "required|integer",
        "koli_data*.awb_url" => "required|string",
        "koli_data*.created_at" => "required|date_format:Y-m-d H:i:s",
        "koli_data*.koli_chargeable_weight" => "required|integer",
        "koli_data*.koli_width" => "required|integer",
        "koli_data*.koli_height" => "required|integer",
        "koli_data*.updated_at" => "required|date_format:Y-m-d H:i:s",
        "koli_data*.koli_description" => "required|string",
        "koli_data*.koli_formula_id" => "required|string",
        "koli_data*.connote_id" => "required|uuid",
        "koli_data*.koli_volume" => "required|integer",
        "koli_data*.koli_weight" => "required|integer",
        "koli_data*.koli_id" => "required|uuid",
        "koli_data*.koli_code" => "required|string",
        "currentLocation*.name" => "required|string",
        "currentLocation*.code" => "required|string",
        "currentLocation*.type" => "required|string",
    ];
}
